# Generated by Django 3.2.12 on 2023-02-01 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('exemple_file', models.FileField(blank=True, null=True, upload_to='posts/examples')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/%d/')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posty',
            },
            bases=(models.Model, posts.models.CheckAgeMixin),
        ),
    ]
