# Generated by Django 4.0.6 on 2022-08-25 18:38

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0008_alter_organizer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=500)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='tournament_calculating/images/%Y/%m/%d/')),
                ('tournaments', models.ManyToManyField(related_name='participants', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Zawodnik',
                'verbose_name_plural': 'Zawodnicy',
            },
        ),
    ]
