# Generated by Django 3.2.12 on 2023-02-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color_fighter_one',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('orange', 'orange)'), ('pink', 'pink'), ('white', 'white'), ('black', 'black)'), ('pink', 'pink')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='color_fighter_two',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('orange', 'orange)'), ('pink', 'pink'), ('white', 'white'), ('black', 'black)'), ('pink', 'pink')], max_length=30, null=True),
        ),
    ]
