# Generated by Django 3.2.12 on 2022-12-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='fight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_of_fight', to='tournament_calculating.fight'),
        ),
        migrations.AlterField(
            model_name='round',
            name='result',
            field=models.CharField(choices=[('0', 'win'), ('1', 'lose'), ('2', 'remis'), ('3', 'no result'), ('4', 'no fight'), ('5', 'no status')], max_length=1, null=True),
        ),
    ]
