# Generated by Django 3.2.12 on 2022-12-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0002_auto_20221205_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_of_group', to='tournament_calculating.group'),
        ),
    ]
