# Generated by Django 4.0.6 on 2022-08-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_organizer_options'),
        ('tournament_calculating', '0002_fight_round_group_fight_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='tournament_calculating.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(default=1, related_name='groups', to='tournament_calculating.participant'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournaments',
            field=models.ManyToManyField(default=1, related_name='participants', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='round',
            name='fight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_of_fight', to='tournament_calculating.fight'),
        ),
    ]
