# Generated by Django 3.2.12 on 2023-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0003_auto_20230220_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color_fighter_one',
            field=models.CharField(choices=[('lemonchiffon', 'żółty'), ('lightgreen', 'zielony'), ('powderblue', 'niebieski'), ('coral', 'czerwony'), ('darkorange', 'pomarańczowy'), ('thistle', 'fioletowy'), ('floralwhite', 'biały'), ('peru', 'brązowy'), ('pink', 'różowy'), ('darkgrey', 'szary')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='color_fighter_two',
            field=models.CharField(choices=[('lemonchiffon', 'żółty'), ('lightgreen', 'zielony'), ('powderblue', 'niebieski'), ('coral', 'czerwony'), ('darkorange', 'pomarańczowy'), ('thistle', 'fioletowy'), ('floralwhite', 'biały'), ('peru', 'brązowy'), ('pink', 'różowy'), ('darkgrey', 'szary')], max_length=30, null=True),
        ),
    ]
