# Generated by Django 3.2.12 on 2022-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0003_round_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
