# Generated by Django 3.2.12 on 2022-12-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0004_round_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
