# Generated by Django 3.2.12 on 2023-02-27 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament_calculating', '0004_auto_20230220_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='points_fighter_one',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('dyskwalifikacja', 'dyskwalifikacja'), ('poddanie', 'poddanie'), ('wycofanie', 'wycofanie'), ('średnia', 'średnia'), ('kontuzja', 'kontuzja')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='points_fighter_two',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('dyskwalifikacja', 'dyskwalifikacja'), ('poddanie', 'poddanie'), ('wycofanie', 'wycofanie'), ('średnia', 'średnia'), ('kontuzja', 'kontuzja')], max_length=20, null=True),
        ),
    ]
