# Generated by Django 3.2.12 on 2022-12-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0005_fight_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='fighter_one_points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='fighter_two_points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
