# Generated by Django 3.2.12 on 2023-03-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('tournament_calculating', '0005_auto_20230227_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantgroup',
            name='tournament_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
    ]
