# Generated by Django 3.2.12 on 2022-12-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0006_auto_20221205_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='fighter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_of_participant', to='tournament_calculating.participant'),
        ),
    ]
