# Generated by Django 3.2.12 on 2023-03-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0006_participantgroup_tournament_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantgroup',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
