# Generated by Django 3.2.12 on 2023-03-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0007_rename_tournament_id_participantgroup_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantgroup',
            name='tournament_amount_rounds',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
