# Generated by Django 3.2.12 on 2022-12-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0007_alter_round_fighter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='points',
            new_name='points_fighter_one',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='result',
            new_name='result_figter_one',
        ),
        migrations.AddField(
            model_name='round',
            name='points_fighter_two',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='result_figter_two',
            field=models.CharField(choices=[('0', 'win'), ('1', 'lose'), ('2', 'remis'), ('3', 'no result'), ('4', 'no fight'), ('5', 'no status')], max_length=1, null=True),
        ),
    ]
