# Generated by Django 3.2.12 on 2022-12-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0008_auto_20221212_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='group_points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
