# Generated by Django 3.2.12 on 2023-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0008_participantgroup_tournament_amount_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantgroup',
            name='round_average',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
