# Generated by Django 3.2.12 on 2022-12-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0009_participant_group_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fighter_one_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='fighter_two_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
