# Generated by Django 3.2.12 on 2023-03-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0009_participantgroup_round_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantgroup',
            name='tournament_points_modified',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
