# Generated by Django 3.2.12 on 2022-12-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0010_auto_20221226_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='points_average',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
