# Generated by Django 3.2.12 on 2023-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0010_participantgroup_tournament_points_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantgroup',
            name='tournament_points_modifeied',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
