# Generated by Django 3.2.12 on 2023-03-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0011_participantgroup_tournament_points_modifeied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantgroup',
            name='tournament_points_modifeied',
        ),
    ]
