# Generated by Django 3.2.12 on 2023-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0011_participant_points_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='result_figter_one',
            field=models.CharField(choices=[('0', 'win'), ('1', 'lose'), ('2', 'draw'), ('3', 'no result'), ('4', 'no fight'), ('5', 'no status')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='result_figter_two',
            field=models.CharField(choices=[('0', 'win'), ('1', 'lose'), ('2', 'draw'), ('3', 'no result'), ('4', 'no fight'), ('5', 'no status')], max_length=1, null=True),
        ),
    ]
