# Generated by Django 3.2.12 on 2023-04-04 10:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0012_remove_participantgroup_tournament_points_modifeied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
