# Generated by Django 3.2.12 on 2023-01-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0014_auto_20230104_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='fighter_one_final_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='fighter_two_final_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='color_fighter_one',
            field=models.CharField(choices=[('lemonchiffon', 'żółty'), ('lightgreen', 'zielony'), ('powderblue', 'niebieski'), ('coral', 'czerwony'), ('darkorange', 'pomarańczowy'), ('thistle', 'fioletowy'), ('darkblue', 'granatowy'), ('darkslategray', 'czarny'), ('floralwhite', 'biały'), ('peru', 'brązowy'), ('pink', 'różowy'), ('darkgrey', 'szary')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='color_fighter_two',
            field=models.CharField(choices=[('lemonchiffon', 'żółty'), ('lightgreen', 'zielony'), ('powderblue', 'niebieski'), ('coral', 'czerwony'), ('darkorange', 'pomarańczowy'), ('thistle', 'fioletowy'), ('darkblue', 'granatowy'), ('darkslategray', 'czarny'), ('floralwhite', 'biały'), ('peru', 'brązowy'), ('pink', 'różowy'), ('darkgrey', 'szary')], max_length=30, null=True),
        ),
    ]
