# Generated by Django 3.2.12 on 2023-04-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0014_alter_participant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='points_fighter_one',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('dyskwalifikacja', 'dyskwalifikacja'), ('poddanie', 'poddanie'), ('wycofanie', 'wycofanie'), ('średnia', 'średnia'), ('kontuzja', 'kontuzja')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='points_fighter_two',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('dyskwalifikacja', 'dyskwalifikacja'), ('poddanie', 'poddanie'), ('wycofanie', 'wycofanie'), ('średnia', 'średnia'), ('kontuzja', 'kontuzja')], max_length=20, null=True),
        ),
    ]
