# Generated by Django 3.2.12 on 2023-01-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0015_auto_20230109_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='fighter',
        ),
        migrations.AddField(
            model_name='round',
            name='fighter_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_of_participant_one', to='tournament_calculating.participant'),
        ),
        migrations.AddField(
            model_name='round',
            name='fighter_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_of_participant_two', to='tournament_calculating.participant'),
        ),
    ]
