# Generated by Django 3.2.12 on 2023-01-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0016_auto_20230109_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='fighter_one_final_points',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='fighter_two_final_points',
        ),
    ]
