# Generated by Django 3.2.12 on 2023-01-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0018_fight_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='result_figter_one',
        ),
        migrations.RemoveField(
            model_name='round',
            name='result_figter_two',
        ),
        migrations.AddField(
            model_name='round',
            name='result_fighter_one',
            field=models.CharField(choices=[('0', 'win'), ('1', 'lose'), ('2', 'draw'), ('3', 'no result'), ('4', 'no fight'), ('5', 'no status'), ('6', 'disqualification'), ('7', 'injury'), ('8', 'absence'), ('9', 'other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='result_fighter_two',
            field=models.CharField(choices=[('0', 'win'), ('1', 'lose'), ('2', 'draw'), ('3', 'no result'), ('4', 'no fight'), ('5', 'no status'), ('6', 'disqualification'), ('7', 'injury'), ('8', 'absence'), ('9', 'other')], max_length=1, null=True),
        ),
    ]
