# Generated by Django 3.2.12 on 2023-01-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0019_auto_20230109_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='resolved_fighter_one',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='resolved_fighter_two',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
