# Generated by Django 3.2.12 on 2023-01-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0020_auto_20230109_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='resolved_fighter_one',
        ),
        migrations.RemoveField(
            model_name='round',
            name='resolved_fighter_two',
        ),
        migrations.RemoveField(
            model_name='round',
            name='result_fighter_one',
        ),
        migrations.RemoveField(
            model_name='round',
            name='result_fighter_two',
        ),
        migrations.AlterField(
            model_name='round',
            name='points_fighter_one',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('draw', '12'), ('no result', '13'), ('no fight', '14'), ('no status', '15'), ('disqualification', '16'), ('injury', '17'), ('absence', '18'), ('other', '19')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='points_fighter_two',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('draw', '12'), ('no result', '13'), ('no fight', '14'), ('no status', '15'), ('disqualification', '16'), ('injury', '17'), ('absence', '18'), ('other', '19')], max_length=20, null=True),
        ),
    ]
