# Generated by Django 3.2.12 on 2023-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0022_auto_20230110_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='points_fighter_one',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('draw', 'remis'), ('brak rezultatu', 'brak rezultatu'), ('nie było walki', 'nie było walki'), ('brak statusu', 'brak statusu'), ('dyskwalifikacja', 'dyskwalifikacja'), ('kontuzja', 'kontuzja'), ('nieobecność', 'nieobecność'), ('inne', 'inne'), ('poddanie', 'poddanie')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='points_fighter_two',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('draw', 'remis'), ('brak rezultatu', 'brak rezultatu'), ('nie było walki', 'nie było walki'), ('brak statusu', 'brak statusu'), ('dyskwalifikacja', 'dyskwalifikacja'), ('kontuzja', 'kontuzja'), ('nieobecność', 'nieobecność'), ('inne', 'inne'), ('poddanie', 'poddanie')], max_length=20, null=True),
        ),
    ]
