# Generated by Django 3.2.12 on 2023-01-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0023_auto_20230110_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='number_outgoing',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
