# Generated by Django 3.2.12 on 2023-01-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0024_group_number_outgoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_outgoing',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
    ]
