# Generated by Django 3.2.12 on 2023-01-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0026_auto_20230116_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='points_fighter_one',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('kontuzja', 'kontuzja'), ('dyskwalifikacja', 'dyskwalifikacja'), ('poddanie', 'poddanie'), ('wycofanie', 'wycofanie'), ('brak rezultatu', 'brak rezultatu')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='points_fighter_two',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('kontuzja', 'kontuzja'), ('dyskwalifikacja', 'dyskwalifikacja'), ('poddanie', 'poddanie'), ('wycofanie', 'wycofanie'), ('brak rezultatu', 'brak rezultatu')], max_length=20, null=True),
        ),
    ]
