# Generated by Django 3.2.12 on 2023-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0027_auto_20230116_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='round_average',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
