# Generated by Django 3.2.12 on 2023-01-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0028_participant_round_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='amount_rounds',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
