# Generated by Django 3.2.12 on 2023-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0029_participant_amount_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='amount_rounds',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='points_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='round_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
