# Generated by Django 3.2.12 on 2023-01-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0030_auto_20230118_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='amount_rounds',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='points_average',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='round_average',
            field=models.FloatField(default=0, null=True),
        ),
    ]
