# Generated by Django 3.2.12 on 2023-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0036_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='groups', to='tournament_calculating.Participant'),
        ),
    ]
