# Generated by Django 3.2.12 on 2023-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0037_alter_group_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tournaments_average',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_disqualifications',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_doubles',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_hands',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_injuries',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_losses',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_opponent_injuries',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_surrenders',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments_wins',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='groups', to='tournament_calculating.Participant'),
        ),
    ]
