# Generated by Django 3.2.12 on 2023-01-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0040_alter_participation_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tournament_average',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_disqualifications',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_doubles',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_hands',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_injuries',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_losses',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_opponent_injuries',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_points',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_surrenders',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament_wins',
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_average',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_disqualifications',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_doubles',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_hands',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_injuries',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_losses',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_opponent_injuries',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_surrenders',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament_wins',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
