# Generated by Django 3.2.12 on 2023-01-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0041_auto_20230131_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='strugglers',
            field=models.ManyToManyField(through='tournament_calculating.Participation', to='tournament_calculating.Participant'),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='groups', to='tournament_calculating.Participant'),
        ),
    ]
