# Generated by Django 3.2.12 on 2023-01-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0042_auto_20230131_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='strugglers',
            field=models.ManyToManyField(to='tournament_calculating.Participant'),
        ),
    ]
