# Generated by Django 3.2.12 on 2023-01-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0043_alter_group_strugglers'),
    ]

    operations = [
    ]
