# Generated by Django 3.2.12 on 2023-01-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0044_auto_20230131_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='strugglers',
        ),
    ]
