# Generated by Django 3.2.12 on 2023-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0045_remove_group_strugglers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='strugglers',
            field=models.ManyToManyField(to='tournament_calculating.Participant'),
        ),
    ]
