# Generated by Django 3.2.12 on 2023-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0047_auto_20230131_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='strugglers',
            field=models.ManyToManyField(through='tournament_calculating.Participation', to='tournament_calculating.Participant'),
        ),
    ]
