# Generated by Django 3.2.12 on 2023-01-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0048_alter_group_strugglers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='strugglers',
        ),
    ]
