# Generated by Django 3.2.12 on 2023-01-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0050_delete_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_points', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_average', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_wins', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_losses', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_doubles', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_hands', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_disqualifications', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_injuries', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_surrenders', models.PositiveSmallIntegerField(default=0, null=True)),
                ('tournament_opponent_injuries', models.PositiveSmallIntegerField(default=0, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_calculating.group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_calculating.participant')),
            ],
        ),

    ]
