# Generated by Django 3.2.12 on 2023-01-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0051_auto_20230131_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='strugglers',
            field=models.ManyToManyField(through='tournament_calculating.Participation', to='tournament_calculating.Participant'),
        ),
    ]
