# Generated by Django 3.2.12 on 2023-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_average',
            field=models.FloatField(null=True),
        ),
    ]
