# Generated by Django 3.2.12 on 2023-04-04 10:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
