# Generated by Django 4.0.6 on 2022-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_organizer_image_organizer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
