# Generated by Django 3.2.12 on 2023-02-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament_calculating', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalFight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('rounds', models.PositiveSmallIntegerField(null=True)),
                ('final_fighter_one_points', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_fighter_two_points', models.PositiveSmallIntegerField(default=0, null=True)),
                ('resolved', models.BooleanField(default=False, null=True)),
                ('final_fighter_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_fighters_one', to='tournament_calculating.participant')),
                ('final_fighter_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_fighters_two', to='tournament_calculating.participant')),
            ],
            options={
                'verbose_name': 'Walka',
                'verbose_name_plural': 'Walki',
            },
        ),
        migrations.CreateModel(
            name='Finalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_points', models.PositiveSmallIntegerField(default=0, null=True)),
                ('test_points', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_points_average', models.PositiveSmallIntegerField(default=0, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalists', to='tournament_calculating.group')),
            ],
            options={
                'verbose_name': 'Finalista',
                'verbose_name_plural': 'Finaliści',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(choices=[('złoto', 'złoto'), ('srebro', 'srebro'), ('brąz', 'brąz')], max_length=20, null=True)),
                ('participant', models.ManyToManyField(related_name='medals', to='tournament_calculating.Participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('color_fighter_one', models.CharField(choices=[('lemonchiffon', 'żółty'), ('lightgreen', 'zielony'), ('powderblue', 'niebieski'), ('coral', 'czerwony'), ('darkorange', 'pomarańczowy'), ('thistle', 'fioletowy'), ('darkblue', 'granatowy'), ('darkslategray', 'czarny'), ('floralwhite', 'biały'), ('peru', 'brązowy'), ('pink', 'różowy'), ('darkgrey', 'szary')], max_length=30, null=True)),
                ('color_fighter_two', models.CharField(choices=[('lemonchiffon', 'żółty'), ('lightgreen', 'zielony'), ('powderblue', 'niebieski'), ('coral', 'czerwony'), ('darkorange', 'pomarańczowy'), ('thistle', 'fioletowy'), ('darkblue', 'granatowy'), ('darkslategray', 'czarny'), ('floralwhite', 'biały'), ('peru', 'brązowy'), ('pink', 'różowy'), ('darkgrey', 'szary')], max_length=30, null=True)),
                ('number_outgoing', models.PositiveSmallIntegerField(default=0, null=True)),
                ('stage_participants', models.ManyToManyField(related_name='stages', to='tournament_calculating.Participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantFinalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_points', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_average', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_wins', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_losses', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_doubles', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_hands', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_disqualifications', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_injuries', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_surrenders', models.PositiveSmallIntegerField(default=0, null=True)),
                ('final_opponent_injuries', models.PositiveSmallIntegerField(default=0, null=True)),
                ('finalist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finals.finalist')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament_calculating.participant')),
            ],
        ),
        migrations.CreateModel(
            name='FinalRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('final_points_fighter_one', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('draw', 'remis'), ('brak rezultatu', 'brak rezultatu'), ('nie było walki', 'nie było walki'), ('brak statusu', 'brak statusu'), ('dyskwalifikacja', 'dyskwalifikacja'), ('kontuzja', 'kontuzja'), ('nieobecność', 'nieobecność'), ('inne', 'inne'), ('poddanie', 'poddanie')], max_length=20, null=True)),
                ('final_points_fighter_two', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('draw', 'remis'), ('brak rezultatu', 'brak rezultatu'), ('nie było walki', 'nie było walki'), ('brak statusu', 'brak statusu'), ('dyskwalifikacja', 'dyskwalifikacja'), ('kontuzja', 'kontuzja'), ('nieobecność', 'nieobecność'), ('inne', 'inne'), ('poddanie', 'poddanie')], max_length=20, null=True)),
                ('final_fight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_final_fight', to='finals.finalfight')),
                ('final_fighter_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_rounds_participant_one', to='tournament_calculating.participant')),
                ('final_fighter_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_rounds_participant_two', to='tournament_calculating.participant')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_of_stage', to='finals.stage')),
            ],
            options={
                'verbose_name': 'Runda finałowa',
                'verbose_name_plural': 'Rundy finałowe',
            },
        ),
        migrations.AddField(
            model_name='finalist',
            name='participants',
            field=models.ManyToManyField(through='finals.ParticipantFinalist', to='tournament_calculating.Participant'),
        ),
        migrations.AddField(
            model_name='finalfight',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='finals.stage'),
        ),
        migrations.AddField(
            model_name='finalfight',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_fights', to='tournaments.tournament'),
        ),
    ]
