# Generated by Django 3.2.12 on 2023-01-11 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_calculating', '0024_group_number_outgoing'),
        ('finals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalist',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalists', to='tournament_calculating.group'),
        ),
    ]
